---

- hosts: all
  become: true
  tasks:

    - name: install apache and php packages
      package:
        name: 
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes

    - name: run systemctl to start httpd service on CentOS
      ansible.builtin.systemd:
        state: started
        enabled: yes
        name: httpd
      when: ansible_distribution == "CentOS"

    - name: run service and add port 80 to firewall on CentOS
      ansible.builtin.command: "firewall-cmd --add-port=80/tcp"
      when: ansible_distribution == "CentOS"
