---

- hosts: all
  become: true
  tasks:

    - name: remove apache and php packages (Ubuntu)
      apt:
        name: 
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: absent
      when: ansible_distribution == "Ubuntu"

    - name: remove apache and php packages (CentOS)
      yum:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: absent
      when: ansible_distribution == "CentOS"

