---

- hosts: web_servers
  become: true
  tasks:

    - name: remove apache and php packages (Ubuntu)
      tags: always
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: absent
      when: ansible_distribution == "Ubuntu"

    - name: remove apache and php packages (CentOS)
      tags: always
      yum:
        name:
          - httpd
          - php
        state: absent
      when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:

    - name: remove mariadb package
      tags: db, mariadb
      package:
        name: mariadb-server
        state: absent

    - name: remove port 80 from firewall (CentOS)
      tags: db, centos, mariadb
      ansible.builtin.command: "firewall-cmd --remove-port=80/tcp"
      when: ansible_distribution == "CentOS"

