---

- hosts: all
  become: true
  pre_tasks:
    
    - name: update repository index (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: update repository index (CentOS)
      tags: always
      yum:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"

- hosts: web_servers
  become: true
  tasks:

    - name: install apache and php packages (Ubuntu)
      tags: apache,apache2,ubuntu
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache and php packages (CentOS)
      tags: apache,httpd,centos
      yum:
        name: 
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"

    - name: enable and start httpd service (CentOS)
      tags: centos,systemd
      systemd:
        state: started
        enabled: yes
        name: httpd
      when: ansible_distribution == "CentOS"

    - name: add port 80 to firewall (CentOS)
      tags: centos,firewall
      command: "firewall-cmd --add-port=80/tcp"
      when: ansible_distribution == "CentOS"

    - name: change contact ServerEmail for apache (Ubuntu)
      tags: apache,ubuntu,httpd
      lineinfile:
        path: /etc/apache2/conf-available/security.conf
        regexp: '^ServerSignature'
        line: "ServerSignature EMail\nServerAdmin foo@bar.com"
      when: ansible_distribution == "Ubuntu"
      register: httpd_ubuntu

    - name: restart apache2 (Ubuntu)
      tags: apache,ubuntu,systemd,httpd
      systemd:
        name: apache2
        state: restarted
      when: httpd_ubuntu.changed

    - name: change contact ServerEmail for httpd (CentOS)
      tags: apache,centos,httpd
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: "ServerAdmin foo@bar.com"
      when: ansible_distribution == "CentOS"
      register: httpd_centos

    - name: restart httpd (CentOS)
      tags: apache,centos,systemd,httpd
      systemd:
        name: httpd
        state: restarted
      when: httpd_centos.changed

    - name: copy html files for website
      tags: apache,apache2,httpd
      copy:
        src: site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb package
      tags: db,mariadb
      package:
        name: mariadb-server
        state: latest

    - name: enable and start mariadb service (CentOS)
      tags: db,centos,mariadb
      ansible.builtin.systemd:
        state: started
        enabled: yes
        name: mariadb
      when: ansible_distribution == "CentOS"
