---

- hosts: all
  become: true
  pre_tasks:
    
    - name: update repository index (Ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false #this ensures that updating repo index NEVER REPORTS "CHANGED" STATUS
      when: ansible_distribution == "Ubuntu"

    - name: update repository index (CentOS)
      tags: always
      yum:
        update_cache: yes
      changed_when: false #this ensures that updating repo index NEVER REPORTS "CHANGED" STATUS
      when: ansible_distribution == "CentOS"

- hosts: all
  become: true
  tasks:
    
    #This play here is redundant BUT can be useful when trying to CHANGE or REVOKE ssh key on our servers (revoke by setting state: absent)
    - name: add ssh key for josh
      authorized_key:
        user: josh
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDlLjsHU/MjMF2zHfaG0L4Kr+NogSRNryicprq/9WG9Y ansible" #public key
        state: present

- hosts: web_servers
  become: true
  tasks:

    - name: install apache and php packages (Ubuntu)
      tags: apache,apache2,ubuntu
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache and php packages (CentOS)
      tags: apache,httpd,centos
      yum:
        name: 
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"

    #By default CentOS doesn't start services after installation
    - name: enable and start httpd service (CentOS)
      tags: centos,systemd
      systemd:
        state: started
        enabled: yes
        name: httpd
      when: ansible_distribution == "CentOS"

    #By default CentOS doesn't open appropriate ports on firewall
    - name: add port 80 to firewall (CentOS)
      tags: centos,firewall
      command: "firewall-cmd --add-port=80/tcp"
      when: ansible_distribution == "CentOS"

    - name: change contact ServerEmail for apache (Ubuntu)
      tags: apache,ubuntu,httpd
      lineinfile:
        path: /etc/apache2/conf-available/security.conf
        regexp: '^ServerSignature'
        line: "ServerSignature EMail\nServerAdmin foo@bar.com"
      when: ansible_distribution == "Ubuntu"
      register: httpd_ubuntu #Registering state of this play here

    #Restarting apache after making changes to the configuration file for Ubuntu
    - name: restart apache2 (Ubuntu)
      tags: apache,ubuntu,systemd,httpd
      systemd:
        name: apache2
        state: restarted
      when: httpd_ubuntu.changed #Running this play ONLY WHEN httpd_ubuntu has changed

    - name: change contact ServerEmail for httpd (CentOS)
      tags: apache,centos,httpd
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: "ServerAdmin foo@bar.com"
      when: ansible_distribution == "CentOS"
      register: httpd_centos #Registering state of this play here

    #Restarting apache after making changes to the configuration file for CentOS
    - name: restart httpd (CentOS)
      tags: apache,centos,systemd,httpd
      systemd:
        name: httpd
        state: restarted
      when: httpd_centos.changed #Running this play ONLY WHEN httpd_centos has changed

    #Copying HTML file from local machine to all web servers
    - name: copy html files for website
      tags: apache,apache2,httpd
      copy:
        src: site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb package
      tags: db,mariadb
      package:
        name: mariadb-server
        state: latest

    #By default CentOS doesn't start services after installation
    - name: enable and start mariadb service (CentOS)
      tags: db,centos,mariadb
      ansible.builtin.systemd:
        state: started
        enabled: yes
        name: mariadb
      when: ansible_distribution == "CentOS"
