---

- hosts: all
  become: true
  pre_tasks:
    
  - name: update repository index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false #this ensures that updating repo index NEVER REPORTS "CHANGED" STATUS
    when: ansible_distribution == "Ubuntu"

  - name: update repository index (CentOS)
    tags: always
    yum:
      update_cache: yes
    changed_when: false #this ensures that updating repo index NEVER REPORTS "CHANGED" STATUS
    when: ansible_distribution == "CentOS"

- hosts: all
  become: true
  roles:
    - base

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

