- name: install apache and php packages
  tags: apache,apache2,ubuntu
  apt:
    name: 
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: enable and start httpd service
  tags: centos,systemd
  systemd:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

# By default CentOS doesn't open appropriate ports on firewall
- name: add port 80 to firewall (CentOS)
  tags: centos,firewall
  command: "firewall-cmd --add-port=80/tcp"
  when: ansible_distribution == "CentOS"

- name: change contact ServerEmail for apache (Ubuntu)
  tags: apache,ubuntu,httpd
  lineinfile:
    path: /etc/apache2/conf-available/security.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin some@email.net
  when: ansible_distribution == "Ubuntu"
  notify: restart_apache

- name: change contact ServerEmail for httpd (CentOS)
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin some@email.net
  when: ansible_distribution == "CentOS"
  notify: restart_apacge

# Copying HTML file from local machine to all web servers
- name: copy html files for website
  tags: apache,apache2,httpd
  copy:
    src: site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
